/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingsRouteImport } from './routes/writings'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as AutomagicRouteImport } from './routes/automagic'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingsIndexRouteImport } from './routes/writings.index'
import { Route as WritingsSlugRouteImport } from './routes/writings.$slug'
import { Route as ApiPostsRouteImport } from './routes/api/posts'

const WritingsRoute = WritingsRouteImport.update({
  id: '/writings',
  path: '/writings',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomagicRoute = AutomagicRouteImport.update({
  id: '/automagic',
  path: '/automagic',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsIndexRoute = WritingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WritingsRoute,
} as any)
const WritingsSlugRoute = WritingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritingsRoute,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automagic': typeof AutomagicRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/writings': typeof WritingsRouteWithChildren
  '/api/posts': typeof ApiPostsRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/writings/': typeof WritingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automagic': typeof AutomagicRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/posts': typeof ApiPostsRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/writings': typeof WritingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automagic': typeof AutomagicRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/writings': typeof WritingsRouteWithChildren
  '/api/posts': typeof ApiPostsRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/writings/': typeof WritingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/automagic'
    | '/llms.txt'
    | '/writings'
    | '/api/posts'
    | '/writings/$slug'
    | '/writings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/automagic'
    | '/llms.txt'
    | '/api/posts'
    | '/writings/$slug'
    | '/writings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/automagic'
    | '/llms.txt'
    | '/writings'
    | '/api/posts'
    | '/writings/$slug'
    | '/writings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AutomagicRoute: typeof AutomagicRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  WritingsRoute: typeof WritingsRouteWithChildren
  ApiPostsRoute: typeof ApiPostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writings': {
      id: '/writings'
      path: '/writings'
      fullPath: '/writings'
      preLoaderRoute: typeof WritingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automagic': {
      id: '/automagic'
      path: '/automagic'
      fullPath: '/automagic'
      preLoaderRoute: typeof AutomagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/': {
      id: '/writings/'
      path: '/'
      fullPath: '/writings/'
      preLoaderRoute: typeof WritingsIndexRouteImport
      parentRoute: typeof WritingsRoute
    }
    '/writings/$slug': {
      id: '/writings/$slug'
      path: '/$slug'
      fullPath: '/writings/$slug'
      preLoaderRoute: typeof WritingsSlugRouteImport
      parentRoute: typeof WritingsRoute
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WritingsRouteChildren {
  WritingsSlugRoute: typeof WritingsSlugRoute
  WritingsIndexRoute: typeof WritingsIndexRoute
}

const WritingsRouteChildren: WritingsRouteChildren = {
  WritingsSlugRoute: WritingsSlugRoute,
  WritingsIndexRoute: WritingsIndexRoute,
}

const WritingsRouteWithChildren = WritingsRoute._addFileChildren(
  WritingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AutomagicRoute: AutomagicRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  WritingsRoute: WritingsRouteWithChildren,
  ApiPostsRoute: ApiPostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
